[package]
name = "safe_prime_gen_wasm"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
glass_pumpkin = "1.0"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
