name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - run: cargo install wasm-pack
    - name: Pack (wasm)
      run: wasm-pack build --target nodejs
    - run: >
      sed -i ".bak" -e 's/"name": "safe_prime_gen_wasm"/"name": "@xdefi-tech/safe_prime_gen"/g' pkg/package.json
    - run: rm pkg/package.json.bak
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      working-directory: ./pkg
