name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - run: cargo install wasm-pack
    - name: Pack (wasm)
      run: wasm-pack build --target nodejs --out-dir pkg/node
    - name: Pack (wasm)
      run: wasm-pack build --target bundler --out-dir pkg/bundler
    - name: Pack (wasm)
      run: wasm-pack build --target web --out-dir pkg/web
    - run: sh ./post_build.sh
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@xdefi-tech'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      working-directory: ./pkg
